sonar.projectKey=tarea-catalogo
sonar.projectName=Tarea Catalogo
sonar.organization=schiesscl
sonar.host.url=https://sonarcloud.io

sonar.sources=server/src,mockup
sonar.tests=server/tests
sonar.test.inclusions=server/tests/**/*.js

sonar.exclusions=mockup/assets/**,data/**,server/node_modules/**
sonar.sourceEncoding=UTF-8